default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  host: localhost
  database: imobili_development

test:
  <<: *default
  host: localhost
  database: imobili_test

production:
  <<: *default
  database: imobili_production
  username: imobili
  password: <%= ENV['IMOBILI_DATABASE_PASSWORD'] %>
